### ISSUE TITLE
Add the usage of `git lfs` in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by casterkay** [davidorme/pyrealm#144]
To download the large dataset in `pyrealm_build_data/`, the developer needs to run `git lfs pull`. Perhaps it's better to add this step in `CONTRIBUTING.md`. Running code testing without this step will lead to two errors related to the dataset.

**Comment by davidorme** [comment]
I hadn't realised that had made it all the way down into `develop` - I thought the profiling branch was still separate. This file might change (see #140) but I think there's a good chance it will stay in `lfs` because we need a reasonably heavy test for profiling.
