### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mondus** [davidorme/pyrealm#54]
The ICCS RSE Team collectively reviewed this GitHub repository together using the [JOSS](https://joss.readthedocs.io/en/latest/review_criteria.html) and [SSI](https://www.software.ac.uk/resources/online-sustainability-evaluation) review criteria, which we used as the basis of this document. The criteria focus on the quality of the software project as sustainable, open source software. The process included installing and running the software, as well as looking at the associated documentation, metadata and aspects of governance.

The results of the review are captured in a public document.

[ICCS Code Review Output](https://docs.google.com/document/d/1GYVFZ9mskbe4_3bTsVz5scfWonsWOatzMvi0AerIS_E/edit#)
[PyRealm - Sustainability Evaluation](https://docs.google.com/document/d/1ihHFxwW_vopmSal3I0wR-5KgBNQY80Ar6ZJz3Gi02yc/edit)

The recommended actions are included here as a task list which can be checked off once each is raised as a distinct issue. It is recommended that each of these be tagged with a 'Code Review' label.

 - [x] #55
 - [x] #56
 - [x] #57
 - [x] #58
 - [x] #59
 - [x] #60
 - [x] #61
 - [x] #62
 - [x] #63
 - [x] #64
 - [x] #65
 - [x] #66

This issue can be closed when the separate code review tasks are created as their own issues.

**Comment by davidorme** [comment]
* Actions all converted into issues tagged https://github.com/davidorme/pyrealm/labels/code%20review
* Grouped the issues under a project https://github.com/users/davidorme/projects/1/views/1
