### ISSUE TITLE
Change branch name from "master" to "main"

### ISSUE THREAD

**Issue by MarionBWeinzierl** [davidorme/pyrealm#87]
The branch name "master" is discouraged because of historical context (link to slavery). 

Instructions how to do this, for example: https://www.git-tower.com/learn/git/faq/git-rename-master-to-main

**Comment by MarionBWeinzierl** [comment]
The README will need adapting accordingly.

**Comment by davidorme** [comment]
@MarionBWeinzierl I have renamed 'master' and set some basic protection on the new 'main' branch.
